const stickyNote1 = document.getElementById("sn1")
const stickyNote2 = document.getElementById("sn2")
const stickyNote3 = document.getElementById("sn3")
const stickyNote4 = document.getElementById("sn4")
const stickyNote1Header = document.getElementById("sn1header")
const stickyNote2Header = document.getElementById("sn2header")
const stickyNote3Header = document.getElementById("sn3header")
const stickyNote4Header = document.getElementById("sn4header")
